/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CommunityId = IDL.Nat;
export const Time = IDL.Int;
export const Community = IDL.Record({
  'id' : CommunityId,
  'creator' : IDL.Principal,
  'coverImageHash' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
});
export const GroupId = IDL.Nat;
export const Group = IDL.Record({
  'id' : GroupId,
  'creator' : IDL.Principal,
  'coverImageHash' : IDL.Opt(ExternalBlob),
  'communityId' : CommunityId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
});
export const GroupPost = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'groupId' : GroupId,
  'mediaHash' : IDL.Opt(ExternalBlob),
  'mediaType' : IDL.Opt(IDL.Text),
});
export const PostType = IDL.Variant({
  'repost' : IDL.Nat,
  'quote' : IDL.Nat,
  'original' : IDL.Null,
  'reply' : IDL.Nat,
});
export const PostResponse = IDL.Record({
  'id' : IDL.Nat,
  'postType' : PostType,
  'authorUsername' : IDL.Text,
  'likeCount' : IDL.Nat,
  'isRepostedByCurrentUser' : IDL.Bool,
  'authorProfilePictureHash' : IDL.Opt(ExternalBlob),
  'repostCount' : IDL.Nat,
  'createdAt' : Time,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'mediaHash' : IDL.Opt(ExternalBlob),
  'replyCount' : IDL.Nat,
  'mediaType' : IDL.Opt(IDL.Text),
  'editedAt' : IDL.Opt(Time),
  'authorDisplayName' : IDL.Text,
  'isLikedByCurrentUser' : IDL.Bool,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const FollowUserResponse = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'profilePictureHash' : IDL.Opt(ExternalBlob),
});
export const PaginatedFollows = IDL.Record({
  'nextOffset' : IDL.Opt(IDL.Nat),
  'hasMore' : IDL.Bool,
  'users' : IDL.Vec(FollowUserResponse),
});
export const PaginatedPosts = IDL.Record({
  'hasMore' : IDL.Bool,
  'posts' : IDL.Vec(PostResponse),
  'nextCursor' : IDL.Opt(IDL.Nat),
});
export const PaginatedGroupPosts = IDL.Record({
  'hasMore' : IDL.Bool,
  'posts' : IDL.Vec(GroupPost),
  'nextCursor' : IDL.Opt(IDL.Nat),
});
export const GroupMember = IDL.Record({
  'principal' : IDL.Principal,
  'joinedAt' : Time,
});
export const NotificationType = IDL.Variant({
  'repost' : IDL.Nat,
  'like' : IDL.Nat,
  'quote' : IDL.Nat,
  'mention' : IDL.Nat,
  'reply' : IDL.Nat,
  'follow' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'notificationType' : NotificationType,
  'createdAt' : Time,
  'isRead' : IDL.Bool,
  'actorUsername' : IDL.Text,
  'actorPrincipal' : IDL.Principal,
});
export const PaginatedNotifications = IDL.Record({
  'hasMore' : IDL.Bool,
  'notifications' : IDL.Vec(Notification),
  'nextCursor' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'headerImageHash' : IDL.Opt(ExternalBlob),
  'profilePictureHash' : IDL.Opt(ExternalBlob),
});
export const UserProfileResponse = IDL.Record({
  'bio' : IDL.Text,
  'isBlockedByCurrentUser' : IDL.Bool,
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'isMutedByCurrentUser' : IDL.Bool,
  'followersCount' : IDL.Nat,
  'createdAt' : Time,
  'updatedAt' : Time,
  'headerImageHash' : IDL.Opt(ExternalBlob),
  'followingCount' : IDL.Nat,
  'isFollowedByCurrentUser' : IDL.Bool,
  'profilePictureHash' : IDL.Opt(ExternalBlob),
  'postsCount' : IDL.Nat,
});
export const TrendingHashtag = IDL.Record({
  'tag' : IDL.Text,
  'count' : IDL.Nat,
});
export const CommunitySummary = IDL.Record({
  'id' : CommunityId,
  'coverImageHash' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'groupCount' : IDL.Nat,
});
export const GroupSummary = IDL.Record({
  'id' : GroupId,
  'coverImageHash' : IDL.Opt(ExternalBlob),
  'communityId' : CommunityId,
  'name' : IDL.Text,
  'memberCount' : IDL.Nat,
  'description' : IDL.Text,
});
export const PaginatedGroups = IDL.Record({
  'hasMore' : IDL.Bool,
  'groups' : IDL.Vec(GroupSummary),
  'nextCursor' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__blocks' : IDL.Func([], [IDL.Reserved], ['query']),
  '__communitiesGroupsState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__followers' : IDL.Func([], [IDL.Reserved], ['query']),
  '__following' : IDL.Func([], [IDL.Reserved], ['query']),
  '__hashtagIndex' : IDL.Func([], [IDL.Reserved], ['query']),
  '__mutes' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextNotificationId' : IDL.Func([], [IDL.Nat], ['query']),
  '__nextPostId' : IDL.Func([], [IDL.Nat], ['query']),
  '__postLikes' : IDL.Func([], [IDL.Reserved], ['query']),
  '__postReplies' : IDL.Func([], [IDL.Reserved], ['query']),
  '__postReposts' : IDL.Func([], [IDL.Reserved], ['query']),
  '__posts' : IDL.Func([], [IDL.Reserved], ['query']),
  '__repostIndex' : IDL.Func([], [IDL.Reserved], ['query']),
  '__userNotifications' : IDL.Func([], [IDL.Reserved], ['query']),
  '__userPostCounts' : IDL.Func([], [IDL.Reserved], ['query']),
  '__userProfiles' : IDL.Func([], [IDL.Reserved], ['query']),
  '__usernameToUser' : IDL.Func([], [IDL.Reserved], ['query']),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'checkUsernameAvailability' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createCommunity' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [Community],
      [],
    ),
  'createGroup' : IDL.Func(
      [CommunityId, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [Group],
      [],
    ),
  'createGroupPost' : IDL.Func(
      [GroupId, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
      [GroupPost],
      [],
    ),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
      [PostResponse],
      [],
    ),
  'createReply' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
      [PostResponse],
      [],
    ),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'editPost' : IDL.Func([IDL.Nat, IDL.Text], [PostResponse], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunity' : IDL.Func([CommunityId], [IDL.Opt(Community)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [PaginatedFollows],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [PaginatedFollows],
      ['query'],
    ),
  'getGlobalFeed' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Nat],
      [PaginatedPosts],
      ['query'],
    ),
  'getGroup' : IDL.Func([GroupId], [IDL.Opt(Group)], ['query']),
  'getGroupFeed' : IDL.Func(
      [GroupId, IDL.Opt(IDL.Nat), IDL.Nat],
      [PaginatedGroupPosts],
      ['query'],
    ),
  'getGroupMembers' : IDL.Func(
      [GroupId, IDL.Nat, IDL.Nat],
      [IDL.Vec(GroupMember)],
      ['query'],
    ),
  'getGroupPost' : IDL.Func([IDL.Nat], [IDL.Opt(GroupPost)], ['query']),
  'getHomeFeed' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Nat],
      [PaginatedPosts],
      ['query'],
    ),
  'getNotifications' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Nat],
      [PaginatedNotifications],
      ['query'],
    ),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(PostResponse)], ['query']),
  'getPostsByHashtag' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat],
      [PaginatedPosts],
      ['query'],
    ),
  'getPostsByUser' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Nat), IDL.Nat],
      [PaginatedPosts],
      ['query'],
    ),
  'getPostsByUsername' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat],
      [PaginatedPosts],
      ['query'],
    ),
  'getPrincipalByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfileResponse)],
      ['query'],
    ),
  'getReplies' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Nat],
      [PaginatedPosts],
      ['query'],
    ),
  'getTrendingHashtags' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TrendingHashtag)],
      ['query'],
    ),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileResponse)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isGroupMember' : IDL.Func([GroupId, IDL.Principal], [IDL.Bool], ['query']),
  'joinGroup' : IDL.Func([GroupId], [], []),
  'leaveGroup' : IDL.Func([GroupId], [], []),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'listCommunities' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Nat],
      [IDL.Vec(CommunitySummary)],
      ['query'],
    ),
  'listGroupsByCommunity' : IDL.Func(
      [CommunityId, IDL.Opt(IDL.Nat), IDL.Nat],
      [PaginatedGroups],
      ['query'],
    ),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'muteUser' : IDL.Func([IDL.Principal], [], []),
  'quotePost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
      [PostResponse],
      [],
    ),
  'repostPost' : IDL.Func([IDL.Nat], [PostResponse], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchCommunities' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(CommunitySummary)],
      ['query'],
    ),
  'searchGroups' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(GroupSummary)],
      ['query'],
    ),
  'searchPosts' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat],
      [PaginatedPosts],
      ['query'],
    ),
  'searchUsers' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(UserProfileResponse)],
      ['query'],
    ),
  'setProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'undoRepost' : IDL.Func([IDL.Nat], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [], []),
  'unmuteUser' : IDL.Func([IDL.Principal], [], []),
  'updateHeaderImage' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  'updateProfilePicture' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CommunityId = IDL.Nat;
  const Time = IDL.Int;
  const Community = IDL.Record({
    'id' : CommunityId,
    'creator' : IDL.Principal,
    'coverImageHash' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
  });
  const GroupId = IDL.Nat;
  const Group = IDL.Record({
    'id' : GroupId,
    'creator' : IDL.Principal,
    'coverImageHash' : IDL.Opt(ExternalBlob),
    'communityId' : CommunityId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
  });
  const GroupPost = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'groupId' : GroupId,
    'mediaHash' : IDL.Opt(ExternalBlob),
    'mediaType' : IDL.Opt(IDL.Text),
  });
  const PostType = IDL.Variant({
    'repost' : IDL.Nat,
    'quote' : IDL.Nat,
    'original' : IDL.Null,
    'reply' : IDL.Nat,
  });
  const PostResponse = IDL.Record({
    'id' : IDL.Nat,
    'postType' : PostType,
    'authorUsername' : IDL.Text,
    'likeCount' : IDL.Nat,
    'isRepostedByCurrentUser' : IDL.Bool,
    'authorProfilePictureHash' : IDL.Opt(ExternalBlob),
    'repostCount' : IDL.Nat,
    'createdAt' : Time,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'mediaHash' : IDL.Opt(ExternalBlob),
    'replyCount' : IDL.Nat,
    'mediaType' : IDL.Opt(IDL.Text),
    'editedAt' : IDL.Opt(Time),
    'authorDisplayName' : IDL.Text,
    'isLikedByCurrentUser' : IDL.Bool,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const FollowUserResponse = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'profilePictureHash' : IDL.Opt(ExternalBlob),
  });
  const PaginatedFollows = IDL.Record({
    'nextOffset' : IDL.Opt(IDL.Nat),
    'hasMore' : IDL.Bool,
    'users' : IDL.Vec(FollowUserResponse),
  });
  const PaginatedPosts = IDL.Record({
    'hasMore' : IDL.Bool,
    'posts' : IDL.Vec(PostResponse),
    'nextCursor' : IDL.Opt(IDL.Nat),
  });
  const PaginatedGroupPosts = IDL.Record({
    'hasMore' : IDL.Bool,
    'posts' : IDL.Vec(GroupPost),
    'nextCursor' : IDL.Opt(IDL.Nat),
  });
  const GroupMember = IDL.Record({
    'principal' : IDL.Principal,
    'joinedAt' : Time,
  });
  const NotificationType = IDL.Variant({
    'repost' : IDL.Nat,
    'like' : IDL.Nat,
    'quote' : IDL.Nat,
    'mention' : IDL.Nat,
    'reply' : IDL.Nat,
    'follow' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'notificationType' : NotificationType,
    'createdAt' : Time,
    'isRead' : IDL.Bool,
    'actorUsername' : IDL.Text,
    'actorPrincipal' : IDL.Principal,
  });
  const PaginatedNotifications = IDL.Record({
    'hasMore' : IDL.Bool,
    'notifications' : IDL.Vec(Notification),
    'nextCursor' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'headerImageHash' : IDL.Opt(ExternalBlob),
    'profilePictureHash' : IDL.Opt(ExternalBlob),
  });
  const UserProfileResponse = IDL.Record({
    'bio' : IDL.Text,
    'isBlockedByCurrentUser' : IDL.Bool,
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'isMutedByCurrentUser' : IDL.Bool,
    'followersCount' : IDL.Nat,
    'createdAt' : Time,
    'updatedAt' : Time,
    'headerImageHash' : IDL.Opt(ExternalBlob),
    'followingCount' : IDL.Nat,
    'isFollowedByCurrentUser' : IDL.Bool,
    'profilePictureHash' : IDL.Opt(ExternalBlob),
    'postsCount' : IDL.Nat,
  });
  const TrendingHashtag = IDL.Record({ 'tag' : IDL.Text, 'count' : IDL.Nat });
  const CommunitySummary = IDL.Record({
    'id' : CommunityId,
    'coverImageHash' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'groupCount' : IDL.Nat,
  });
  const GroupSummary = IDL.Record({
    'id' : GroupId,
    'coverImageHash' : IDL.Opt(ExternalBlob),
    'communityId' : CommunityId,
    'name' : IDL.Text,
    'memberCount' : IDL.Nat,
    'description' : IDL.Text,
  });
  const PaginatedGroups = IDL.Record({
    'hasMore' : IDL.Bool,
    'groups' : IDL.Vec(GroupSummary),
    'nextCursor' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__blocks' : IDL.Func([], [IDL.Reserved], ['query']),
    '__communitiesGroupsState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__followers' : IDL.Func([], [IDL.Reserved], ['query']),
    '__following' : IDL.Func([], [IDL.Reserved], ['query']),
    '__hashtagIndex' : IDL.Func([], [IDL.Reserved], ['query']),
    '__mutes' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextNotificationId' : IDL.Func([], [IDL.Nat], ['query']),
    '__nextPostId' : IDL.Func([], [IDL.Nat], ['query']),
    '__postLikes' : IDL.Func([], [IDL.Reserved], ['query']),
    '__postReplies' : IDL.Func([], [IDL.Reserved], ['query']),
    '__postReposts' : IDL.Func([], [IDL.Reserved], ['query']),
    '__posts' : IDL.Func([], [IDL.Reserved], ['query']),
    '__repostIndex' : IDL.Func([], [IDL.Reserved], ['query']),
    '__userNotifications' : IDL.Func([], [IDL.Reserved], ['query']),
    '__userPostCounts' : IDL.Func([], [IDL.Reserved], ['query']),
    '__userProfiles' : IDL.Func([], [IDL.Reserved], ['query']),
    '__usernameToUser' : IDL.Func([], [IDL.Reserved], ['query']),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'checkUsernameAvailability' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'createCommunity' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [Community],
        [],
      ),
    'createGroup' : IDL.Func(
        [CommunityId, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [Group],
        [],
      ),
    'createGroupPost' : IDL.Func(
        [GroupId, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
        [GroupPost],
        [],
      ),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
        [PostResponse],
        [],
      ),
    'createReply' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
        [PostResponse],
        [],
      ),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'editPost' : IDL.Func([IDL.Nat, IDL.Text], [PostResponse], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunity' : IDL.Func([CommunityId], [IDL.Opt(Community)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [PaginatedFollows],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [PaginatedFollows],
        ['query'],
      ),
    'getGlobalFeed' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Nat],
        [PaginatedPosts],
        ['query'],
      ),
    'getGroup' : IDL.Func([GroupId], [IDL.Opt(Group)], ['query']),
    'getGroupFeed' : IDL.Func(
        [GroupId, IDL.Opt(IDL.Nat), IDL.Nat],
        [PaginatedGroupPosts],
        ['query'],
      ),
    'getGroupMembers' : IDL.Func(
        [GroupId, IDL.Nat, IDL.Nat],
        [IDL.Vec(GroupMember)],
        ['query'],
      ),
    'getGroupPost' : IDL.Func([IDL.Nat], [IDL.Opt(GroupPost)], ['query']),
    'getHomeFeed' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Nat],
        [PaginatedPosts],
        ['query'],
      ),
    'getNotifications' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Nat],
        [PaginatedNotifications],
        ['query'],
      ),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(PostResponse)], ['query']),
    'getPostsByHashtag' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat],
        [PaginatedPosts],
        ['query'],
      ),
    'getPostsByUser' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Nat), IDL.Nat],
        [PaginatedPosts],
        ['query'],
      ),
    'getPostsByUsername' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat],
        [PaginatedPosts],
        ['query'],
      ),
    'getPrincipalByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfileResponse)],
        ['query'],
      ),
    'getReplies' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Nat],
        [PaginatedPosts],
        ['query'],
      ),
    'getTrendingHashtags' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TrendingHashtag)],
        ['query'],
      ),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileResponse)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isGroupMember' : IDL.Func([GroupId, IDL.Principal], [IDL.Bool], ['query']),
    'joinGroup' : IDL.Func([GroupId], [], []),
    'leaveGroup' : IDL.Func([GroupId], [], []),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'listCommunities' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Nat],
        [IDL.Vec(CommunitySummary)],
        ['query'],
      ),
    'listGroupsByCommunity' : IDL.Func(
        [CommunityId, IDL.Opt(IDL.Nat), IDL.Nat],
        [PaginatedGroups],
        ['query'],
      ),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'muteUser' : IDL.Func([IDL.Principal], [], []),
    'quotePost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
        [PostResponse],
        [],
      ),
    'repostPost' : IDL.Func([IDL.Nat], [PostResponse], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchCommunities' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(CommunitySummary)],
        ['query'],
      ),
    'searchGroups' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(GroupSummary)],
        ['query'],
      ),
    'searchPosts' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat],
        [PaginatedPosts],
        ['query'],
      ),
    'searchUsers' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(UserProfileResponse)],
        ['query'],
      ),
    'setProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'undoRepost' : IDL.Func([IDL.Nat], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [], []),
    'unmuteUser' : IDL.Func([IDL.Principal], [], []),
    'updateHeaderImage' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
    'updateProfilePicture' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };